# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4c7585c1ab3eed24dfb100a4ba7a71b3a5b192c1b6baef911a62bd2a3e97b09a8f1dfe3f8f823ddc8eda4a5d7d3efccb815060d6a57d967a791b0bf388fb5fa

test:
  secret_key_base: 8571a239c0ec99fd34c1b5d5023d1a0fc1d7abbe07b9aa3889aa25f0781f5f68a06f95710558d6b521cf5b5f78354ed384c5345382728a0d20d8a95a66a5006b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
